# Generated by Django 4.2.7 on 2025-08-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WasteClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="waste_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "bmp", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CT", "Chhattisgarh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TG", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UT", "Uttarakhand"),
                            ("WB", "West Bengal"),
                            ("AN", "Andaman and Nicobar"),
                            ("CH", "Chandigarh"),
                            ("DH", "Dadra and Nagar Haveli"),
                            ("DD", "Daman and Diu"),
                            ("DL", "Delhi"),
                            ("JK", "Jammu and Kashmir"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("PY", "Puducherry"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "predicted_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEDICAL", "Medical Waste"),
                            ("E_WASTE", "E-Waste"),
                            ("GENERAL", "General Waste"),
                            ("RECYCLABLE", "Recyclable Waste"),
                            ("NON_RECYCLABLE", "Non-Recyclable Waste"),
                            ("HAZARDOUS", "Hazardous Waste"),
                            ("ORGANIC", "Organic Waste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("waste_description", models.TextField(blank=True)),
                ("disposal_instructions", models.TextField(blank=True)),
                ("state_specific_laws", models.TextField(blank=True)),
                ("authorized_facilities", models.TextField(blank=True)),
                ("health_hazards", models.TextField(blank=True)),
                ("environmental_risks", models.TextField(blank=True)),
                ("precautions", models.TextField(blank=True)),
                ("protective_equipment", models.TextField(blank=True)),
                ("emergency_procedures", models.TextField(blank=True)),
                ("recyclability_info", models.TextField(blank=True)),
                ("cost_implications", models.TextField(blank=True)),
                ("gemini_raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Waste Classification",
                "verbose_name_plural": "Waste Classifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
